/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   cuba-form.html
 */

/// <reference path="cuba-entity-form.d.ts" />
/// <reference path="cuba-service-form.d.ts" />

