/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   cuba-form-behavior.html
 */

/**
 * Exposes bean validation errors.
 */
interface CubaFormBehavior {

  /**
   * Map of errors returned by REST API (bean validation) {fieldPath: concatenatedErrorMessage, ...}.
   */
  serverErrors: object|null|undefined;

  /**
   * Raw list of errors returned by REST API (bean validation).
   */
  rawServerErrors: any[]|null|undefined;
  _clearErrors(): void;
  _handleError(result: any): void;
  _addError(path: any, errorMessage: any): void;
}

declare const CubaFormBehavior: object;
