/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   cuba-service-form.html
 */

/// <reference path="cuba-form-behavior.d.ts" />
/// <reference path="../cuba-app/cuba-app-aware-behavior.d.ts" />

/**
 * `cuba-service-form`
 */
interface CubaServiceFormElement extends Polymer.Element, CubaAppAwareBehavior, CubaFormBehavior {
  serviceName: string|null|undefined;
  method: string|null|undefined;
  params: object|null|undefined;
  readonly result: object|null|undefined;
  ready(): void;

  /**
   * Send data to server.
   */
  submit(): any;
}

interface HTMLElementTagNameMap {
  "cuba-service-form": CubaServiceFormElement;
}
